project:
  type: website

website:
  title: "Naren's Personal Site"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/narenp12
      - icon: linkedin
        href: https://www.linkedin.com/in/naren-p/
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



